### ISSUE TITLE
Blackout map auto change

### ISSUE THREAD

**Issue by HRDWF** [ate47/t8-atian-menu#1]
Every time i inject the menu, it load alcatraz night every time, if i try to change, it load the map then it load back to alcatraz night

**Comment by ate47** [comment]
Disable these configs in the config.gsc file

- force_blackout_gametype
- force_blackout_map

Are you switching using the menu?

**Comment by HRDWF** [comment]
it worked thx, i was switching map with the menu.

**Comment by HRDWF** [comment]
```
// self.force_blackout_map = "wz_escape_alt";
// self.force_blackout_gametype = "warzone_escape_quad_dbno";
```

thix fixed it
