### ISSUE TITLE
Error - November 417 Silver Sunrise

### ISSUE THREAD

**Issue by shadowrun321** [ate47/t8-atian-menu#5]
### Description of the issue

I have problem start BLACKOUT with Core Map + gamemode: heavy and heroes.
When start game show me error - November 417 Silver Sunrise :(

PS: Can I change the value of life? gravity? duration and size of zones?
Thx Fix My Problem! Very Good Job and your WORK! :)

### Do I want to contribute to fix it?

None

**Comment by ate47** [comment]
When you say "heavy and heroes", are you talking about using that in the configs?

```cpp
self.force_blackout_gametype = "warzone_heavy_metal_heroes";
```

Because it can be that you wrote `warzone_heavy_metal`, without the heroes it's a bug with the mode itself.

Also no, I didn't add things like that

**Comment by shadowrun321** [comment]
Hi! Yes! I'm talking about : self.force_blackout_gametype = "warzone_heavy_metal_heroes";
I enter everything as above :( and.. SHOW ERROR!

**Comment by shadowrun321** [comment]
+ Show Me Critical Error, number : 5410065330

**Comment by shadowrun321** [comment]
any solution? :)

**Comment by ate47** [comment]
sorry I was busy with cw, I'm checking that right now

**Comment by shadowrun321** [comment]
Ach... :) ok! I'm waiting... Please tell me if I can do the following in blackout: control zone? or set game time?
Thank You very much! Thx for WORKS! Sorry my english :)

**Comment by ate47** [comment]
It should be fix. 

About the zones or the game time, you don't have such options in this mod, but you can ask the guys on this discord server: https://discord.gg/FUbGY8T

They're doing a lot of Blackout

**Comment by shadowrun321** [comment]
New problem, when I do injection, I get the following message: The index exceeded the limits of the array

**Comment by shadowrun321** [comment]
T7/T8 Compiler version 3.0.6.6, by Serious

Checking client version... (our version is 3000000060006)
223 ms compile time (excluding irony)
 -- 198,9998 ms to build the structure.
 -- 24,0002 ms to commit to binary.

**Comment by ate47** [comment]
This one is an error with the latest version of the compiler itself.

**Comment by shadowrun321** [comment]
Is there any way to fix this?

**Comment by ate47** [comment]
I sent the error to serious, he’ll probably fix it soon
